/****************************
 * AUTO GENERATED BY LAMBDA *
 ****************************/
import {IndividualTickets, Passes } from './pricingTypes'

export const individualTickets: IndividualTickets = { 
	Friday: { 
		 Party:{
			 cost: 20,
			 studentCost: 15,
			 isAvailable: true,
			 priceId: 'price_1PwAoLEWkmdeWsQPhKuSbZsG',
			 studentPriceId: 'price_1PwAofEWkmdeWsQPCooNqfSK'
			 },
		},
	Saturday: { 
		 Dinner:{
			 cost: 42.5,
			 studentCost: 38.5,
			 isAvailable: true,
			 priceId: 'price_1PwAtHEWkmdeWsQPfqWoTVqK',
			 studentPriceId: 'price_1PwAtbEWkmdeWsQPBogwBiqz'
			 },
		 Party:{
			 cost: 25,
			 studentCost: 22,
			 isAvailable: true,
			 priceId: 'price_1PwAozEWkmdeWsQPdB2L4baa',
			 studentPriceId: 'price_1PwApKEWkmdeWsQP92641eG7'
			 },
		 Classes:{
			 cost: 55,
			 studentCost: 55,
			 isAvailable: true,
			 priceId: 'price_1PiMe5EWkmdeWsQP1s1BhBsv',
			 studentPriceId: 'price_1PwAsbEWkmdeWsQPQOCb4Nnv'
			 },
		},
	Sunday: { 
		 Classes:{
			 cost: 55,
			 studentCost: 55,
			 isAvailable: true,
			 priceId: 'price_1PiMwyEWkmdeWsQPo5Tl0V6k',
			 studentPriceId: 'price_1PwAssEWkmdeWsQPf5izl6wp'
			 },
		 Party:{
			 cost: 20,
			 studentCost: 15,
			 isAvailable: true,
			 priceId: 'price_1PwArnEWkmdeWsQPVPmw34jm',
			 studentPriceId: 'price_1PwAsBEWkmdeWsQPr7nYUKnu'
			 },
		},
 }

export const initialSelectedOptions = {
	Friday: { 
		Party: false,
		},
	Saturday: { 
		Dinner: false,
		Party: false,
		Classes: false,
		},
	Sunday: { 
		Classes: false,
		Party: false,
		},
 }

// Binary version = [Friday BiParty,Saturday Class Pass,Saturday Dinner,Saturday Party,Sunday Class Pass,Sunday Party]
export const passes: Passes = {
	'Saturday Pass': {
		 cost: 95,
		 studentCost: 95,
		 isAvailable: true,
		 saving: 27.5,
		 studentSaving: 20.5,
		 combination: ['Saturday Classes', 'Saturday Dinner', 'Saturday Party'],
		 description: "The entire Saturday experience",
		 priceId: 'price_1PZcrKEWkmdeWsQPl1h22Dk4',
		 studentPriceId: 'price_1PiNkwEWkmdeWsQPWabYCO4U'},
	'Class Pass': {
		 cost: 95,
		 studentCost: 95,
		 isAvailable: true,
		 saving: 15,
		 studentSaving: 15,
		 combination: ['Saturday Classes', 'Sunday Classes'],
		 description: "All the classes for the weekend",
		 priceId: 'price_1PiGlOEWkmdeWsQP7DrG63Bh',
		 studentPriceId: 'price_1PwAnJEWkmdeWsQP5nxx9WVb'},
	'Party Pass': {
		 cost: 45,
		 studentCost: 35,
		 isAvailable: true,
		 saving: 20,
		 studentSaving: 17,
		 combination: ['Friday Party', 'Saturday Party', 'Sunday Party'],
		 description: "Party away every single night, the ultimate party weekend",
		 priceId: 'price_1PZctuEWkmdeWsQP4gPCbeER',
		 studentPriceId: 'price_1PgTOHEWkmdeWsQPNMogFUVa'},
	'Dine and Dance Pass': {
		 cost: 60,
		 studentCost: 55,
		 isAvailable: true,
		 saving: 7.5,
		 studentSaving: 5.5,
		 combination: ['Saturday Dinner', 'Saturday Party'],
		 description: "Saturday evening is covered including your food",
		 priceId: 'price_1PwAnfEWkmdeWsQPnaBU07nh',
		 studentPriceId: 'price_1PwAnsEWkmdeWsQPH2MrprVg'},
	'Full Pass': {
		 cost: 105,
		 studentCost: 85,
		 isAvailable: true,
		 saving: 112.5,
		 studentSaving: 115.5,
		 combination: ['Friday Party', 'Saturday Classes', 'Saturday Dinner', 'Saturday Party', 'Sunday Classes', 'Sunday Party'],
		 description: "Everything the festival has at the best rate! If you're looking for the best deal this is it",
		 priceId: 'price_1PwAjVEWkmdeWsQPZ3X074YG',
		 studentPriceId: 'price_1PwAkKEWkmdeWsQPD3GZd6nV'},
	'Sunday Pass': {
		 cost: 59,
		 studentCost: 59,
		 isAvailable: true,
		 saving: 16,
		 studentSaving: 11,
		 combination: ['Sunday Classes', 'Sunday Party'],
		 description: "The whole Sunday experience",
		 priceId: 'price_1PiGJpEWkmdeWsQPbocbo6df',
		 studentPriceId: 'price_1PwAmZEWkmdeWsQP4ytObuGc'},

}

export const fullPassName = Object.keys(passes).at(4)
export const days = ['Friday', 'Saturday', 'Sunday']
export const passTypes = Object.keys(individualTickets['Saturday']).filter((item) => individualTickets['Saturday'][item].isAvailable) //['Party', 'Classes', 'Dinner']

