/****************************
 * AUTO GENERATED BY LAMBDA *
 ****************************/
import {IndividualTickets, Passes } from './pricingTypes'

export const individualTickets: IndividualTickets = { 
	Friday: { 
		 Party:{
			 cost: 15,
			 studentCost: 15,
			 isAvailable: true,
			 priceId: 'price_1PZdG3EWkmdeWsQPrtrfrxtL',
			 studentPriceId: 'price_1PZdG3EWkmdeWsQPrtrfrxtL'
			 },
		},
	Saturday: { 
		 Dinner:{
			 cost: 35,
			 studentCost: 35,
			 isAvailable: true,
			 priceId: 'price_1PZdLDEWkmdeWsQPawG018VY',
			 studentPriceId: 'price_1PZdLDEWkmdeWsQPawG018VY'
			 },
		 Party:{
			 cost: 22,
			 studentCost: 22,
			 isAvailable: true,
			 priceId: 'price_1PZdGnEWkmdeWsQPSM32DRS0',
			 studentPriceId: 'price_1PZdGnEWkmdeWsQPSM32DRS0'
			 },
		 Classes:{
			 cost: 40,
			 studentCost: 40,
			 isAvailable: true,
			 priceId: 'price_1PZdJKEWkmdeWsQP3pwuvPlG',
			 studentPriceId: 'price_1PZdJKEWkmdeWsQP3pwuvPlG'
			 },
		},
	Sunday: { 
		 Classes:{
			 cost: 40,
			 studentCost: 40,
			 isAvailable: true,
			 priceId: 'price_1PZdKcEWkmdeWsQPuTOfpu9Y',
			 studentPriceId: 'price_1PZdKcEWkmdeWsQPuTOfpu9Y'
			 },
		 Party:{
			 cost: 15,
			 studentCost: 15,
			 isAvailable: true,
			 priceId: 'price_1PZdHNEWkmdeWsQPMx12ez1O',
			 studentPriceId: 'price_1PZdHNEWkmdeWsQPMx12ez1O'
			 },
		},
 }

export const initialSelectedOptions = {
	Friday: { 
		Party: false,
		},
	Saturday: { 
		Dinner: false,
		Party: false,
		Classes: false,
		},
	Sunday: { 
		Classes: false,
		Party: false,
		},
 }

// Binary version = [Friday BiParty,Saturday Class Pass,Saturday Dinner,Saturday Party,Sunday Class Pass,Sunday Party]
export const passes: Passes = {
	'Saturday Pass': {
		 cost: 95,
		 studentCost: 95,
		 isAvailable: True,
		 saving: 1,
		 studentSaving: 1,
		 combination: ['Saturday Classes', 'Saturday Dinner', 'Saturday Party'],
		 description: "The entire Saturday experience",
		 priceId: 'price_1PZcrKEWkmdeWsQPl1h22Dk4',
		 studentPriceId: 'price_1PZcrKEWkmdeWsQPl1h22Dk4'},
	'Class Pass': {
		 cost: 65,
		 studentCost: 65,
		 isAvailable: True,
		 saving: 1,
		 studentSaving: 1,
		 combination: ['Saturday Classes', 'Sunday Classes'],
		 description: "All the classes for the weekend",
		 priceId: 'price_1PZcuzEWkmdeWsQPPfjdXeAq',
		 studentPriceId: 'price_1PZcuzEWkmdeWsQPPfjdXeAq'},
	'Party Pass': {
		 cost: 45,
		 studentCost: 35,
		 isAvailable: True,
		 saving: 1,
		 studentSaving: 1,
		 combination: ['Friday Party', 'Saturday Party', 'Sunday Party'],
		 description: "Party away every single night, the ultimate party weekend",
		 priceId: 'price_1PZctuEWkmdeWsQP4gPCbeER',
		 studentPriceId: 'price_1PgTOHEWkmdeWsQPNMogFUVa'},
	'Dine and Dance Pass': {
		 cost: 45,
		 studentCost: 45,
		 isAvailable: True,
		 saving: 1,
		 studentSaving: 1,
		 combination: ['Saturday Dinner', 'Saturday Party'],
		 description: "Saturday evening is covered including your food",
		 priceId: 'price_1PZcwvEWkmdeWsQP15mdAjdB',
		 studentPriceId: 'price_1PZcwvEWkmdeWsQP15mdAjdB'},
	'Full Pass': {
		 cost: 125,
		 studentCost: 110,
		 isAvailable: True,
		 saving: 1,
		 studentSaving: 1,
		 combination: ['Friday Party', 'Saturday Classes', 'Saturday Dinner', 'Saturday Party', 'Sunday Classes', 'Sunday Party'],
		 description: "Everything the festival has at the best rate! If you're looking for the best deal this is it",
		 priceId: 'price_1PhiIlEWkmdeWsQPHit5QAQq',
		 studentPriceId: 'price_1PhiIBEWkmdeWsQPInw95nZm'},
	'Sunday Pass': {
		 cost: 95,
		 studentCost: 95,
		 isAvailable: True,
		 saving: 1,
		 studentSaving: 1,
		 combination: ['Sunday Classes', 'Sunday Party'],
		 description: "The whole Sunday experience",
		 priceId: 'price_1PZcsWEWkmdeWsQP6fnzjInt',
		 studentPriceId: 'price_1PZcsWEWkmdeWsQP6fnzjInt'},

}

export const fullPassName = Object.keys(passes).at(4)
export const days = ['Friday', 'Saturday', 'Sunday']
export const passTypes = Object.keys(individualTickets['Saturday']).filter((item) => individualTickets['Saturday'][item].isAvailable) //['Party', 'Classes', 'Dinner']

