import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import json
import os
import logging
logger = logging.getLogger()
logger.setLevel("INFO")

#TODO before using Make sure MailDev running  npx maildev  --incoming-user "987p6absdkjl" --incoming-pass "875sadv&oa8s7td"

# Configuration
port = 1025
smtp_server = os.environ.get("MAILDEV_IP", "localhost")
login = "987p6absdkjl"  # Your login generated by Mailtrap
password = "875sadv&oa8s7td"  # Your password generated by Mailtrap


def send_test_email(sender_email, receiver_email, subject, html_content, attachents):

  # Create a multipart message and set headers
  message = MIMEMultipart()
  message["From"] = sender_email
  message["To"] = receiver_email
  message["Subject"] = subject

  # Attach the HTML part
  message.attach(MIMEText(html_content, "html"))

  # Send the email
  with smtplib.SMTP(smtp_server, port) as server:
      # server.starttls()
      server.login(login, password)
      server.sendmail(sender_email, receiver_email, message.as_string())

  print('Sent')


def maildev(event,context): 
  sender_email = "mailtrap@localhost"
  receiver_email = "new1@example.com"

  # Email content
  subject = "HTML Email without Attachment"
  html = """\
  <html>
    <body>
      <p>Hi Connor<br>
      This is a <b>test</b> email without an attachment sent using <a href="https://www.python.org">Python</a>.</p>
      <p>Regards,<br>
      MailTrap & Adam
    </body>
  </html>
  """

  send_test_email(sender_email, receiver_email, subject, html, None)

  lambdaResponse = {
          'statusCode': 200,
          'body': json.dumps({ "success": True }),
          "headers": {
              "Content-Type": "application/json"
          }
      }
  logger.info(lambdaResponse)
  return lambdaResponse