name: Deploy preview branch

on:
  push:
    branches:
      - feature/serverless

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: preview
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: rm -rf node_modules && yarn install --frozen-lockfile
    - name: Install Plugin & Deploy
      uses: serverless/github-action@v3.2.0
      with:
        args: -c "cd ./functions && serverless plugin install --name serverless-prune-plugin --legacy-peer-deps && serverless deploy --verbose"
        entrypoint: /bin/sh
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}      
