name: Deploy Python Lambdas to Dev Namespace

on:
  push:
    branches:
      - develop
    paths:
      - '**.py' # Change to the file extension of the language that you are using.

permissions:
  id-token: write
  contents: write

jobs:
  updateDevRecieveStripeUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: unfor19/install-aws-cli-action@v1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::645491919786:role/github-aws-credentials-mlf24-Role-s5Siu9i8MPJB

      - run: zip -jr devRecieveStripeUpdate.zip ./functions/recieveStripeUpdate/
      - run: aws lambda update-function-code --function-name=dev-recieveStripeUpdate --zip-file=fileb://devRecieveStripeUpdate.zip
