name: Merge pricing into pricing-testing
on:
  push:
    branches:
      - pricing

permissions:
  contents: write

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge pricing to pricing-testing branch
        uses: devvspaces/merge-branches@v1
        with:
          token: ${{ github.token }}
          from_branch: pricing
          to_branch: pricing-testing